import { describe, expect, it } from "vitest";
import { encodeWav } from "../kokoro/wav-encoder.js";
import { decodeWav } from "./wav-decoder.js";
import { PiperSynthesisError } from "./piper-error.js";

describe("decodeWav", () => {
  it("decodes a valid WAV generated by encodeWav round-trip", () => {
    const sampleRateHz = 22050;
    const sampleCount = 44100; // 2.0 seconds
    const samples = new Float32Array(sampleCount);
    for (let i = 0; i < sampleCount; i++) {
      samples[i] = 0.3 * Math.sin((2 * Math.PI * 440 * i) / sampleRateHz);
    }

    const wavBytes = encodeWav(samples, sampleRateHz);
    const decoded = decodeWav(wavBytes);

    expect(decoded.sampleRateHz).toBe(22050);
    expect(decoded.numChannels).toBe(1);
    expect(decoded.bitsPerSample).toBe(16);
    expect(decoded.dataByteOffset).toBe(44);
    expect(decoded.dataByteLength).toBe(sampleCount * 2);
    expect(decoded.durationMs).toBe(2000);
  });

  it("handles integer durationMs rounding correctly", () => {
    // 35,420 samples at 22,050 Hz = 1606.3492... ms -> Math.round -> 1606
    const sampleRateHz = 22050;
    const sampleCount = 35420;
    const samples = new Float32Array(sampleCount);
    const wavBytes = encodeWav(samples, sampleRateHz);
    const decoded = decodeWav(wavBytes);

    expect(decoded.durationMs).toBe(1606);
    expect(Number.isInteger(decoded.durationMs)).toBe(true);
  });

  it("dynamically scans chunks when extra LIST/fact metadata chunks precede data", () => {
    // Build a WAV with an injected 'LIST' chunk between 'fmt ' and 'data'
    const sampleRateHz = 16000;
    const numChannels = 1;
    const bitsPerSample = 16;
    const dataSize = 3200; // 100ms at 16kHz mono 16-bit

    const extraChunkPayload = new TextEncoder().encode("INFOINAMCustomTitle"); // 19 bytes (odd length, tests word alignment padding!)
    const extraChunkPaddedSize = extraChunkPayload.length + (extraChunkPayload.length % 2);

    const fmtChunkSize = 16;
    const totalSize = 12 + (8 + fmtChunkSize) + (8 + extraChunkPaddedSize) + (8 + dataSize);

    const buffer = new Uint8Array(totalSize);
    const view = new DataView(buffer.buffer);

    // RIFF header
    buffer.set([0x52, 0x49, 0x46, 0x46], 0); // RIFF
    view.setUint32(4, totalSize - 8, true);
    buffer.set([0x57, 0x41, 0x56, 0x45], 8); // WAVE

    let offset = 12;

    // 'fmt ' chunk
    buffer.set([0x66, 0x6d, 0x74, 0x20], offset); // fmt
    view.setUint32(offset + 4, fmtChunkSize, true);
    view.setUint16(offset + 8, 1, true); // PCM
    view.setUint16(offset + 10, numChannels, true);
    view.setUint32(offset + 12, sampleRateHz, true);
    view.setUint32(offset + 16, sampleRateHz * numChannels * (bitsPerSample / 8), true);
    view.setUint16(offset + 20, numChannels * (bitsPerSample / 8), true);
    view.setUint16(offset + 22, bitsPerSample, true);
    offset += 8 + fmtChunkSize;

    // 'LIST' chunk with odd length payload + padding byte
    buffer.set([0x4c, 0x49, 0x53, 0x54], offset); // LIST
    view.setUint32(offset + 4, extraChunkPayload.length, true);
    buffer.set(extraChunkPayload, offset + 8);
    offset += 8 + extraChunkPaddedSize;

    // 'data' chunk
    buffer.set([0x64, 0x61, 0x74, 0x61], offset); // data
    view.setUint32(offset + 4, dataSize, true);

    const decoded = decodeWav(buffer);
    expect(decoded.sampleRateHz).toBe(16000);
    expect(decoded.numChannels).toBe(1);
    expect(decoded.bitsPerSample).toBe(16);
    expect(decoded.dataByteLength).toBe(3200);
    expect(decoded.dataByteOffset).toBeGreaterThan(44);
    expect(decoded.durationMs).toBe(100);
  });

  it("throws DECODE_FAILED on data shorter than 12 bytes", () => {
    expect(() => decodeWav(new Uint8Array([1, 2, 3]))).toThrowError(PiperSynthesisError);
    try {
      decodeWav(new Uint8Array([1, 2, 3]));
    } catch (err: unknown) {
      const error = err as PiperSynthesisError;
      expect(error.code).toBe("DECODE_FAILED");
    }
  });

  it("throws DECODE_FAILED when RIFF/WAVE magic bytes are missing", () => {
    const badBytes = new Uint8Array(44);
    expect(() => decodeWav(badBytes)).toThrowError(PiperSynthesisError);
    try {
      decodeWav(badBytes);
    } catch (err: unknown) {
      const error = err as PiperSynthesisError;
      expect(error.code).toBe("DECODE_FAILED");
    }
  });

  it("throws DECODE_FAILED when chunk declares length exceeding buffer bounds (truncated)", () => {
    const buffer = new Uint8Array(20);
    const view = new DataView(buffer.buffer);
    buffer.set([0x52, 0x49, 0x46, 0x46], 0); // RIFF
    view.setUint32(4, 100, true);
    buffer.set([0x57, 0x41, 0x56, 0x45], 8); // WAVE
    buffer.set([0x66, 0x6d, 0x74, 0x20], 12); // fmt
    view.setUint32(16, 50, true); // Declares 50 bytes, but buffer only has 20 total

    expect(() => decodeWav(buffer)).toThrowError(PiperSynthesisError);
    try {
      decodeWav(buffer);
    } catch (err: unknown) {
      const error = err as PiperSynthesisError;
      expect(error.code).toBe("DECODE_FAILED");
      expect(error.message).toContain("Truncated WAV chunk");
    }
  });

  it("throws DECODE_FAILED when 'fmt ' chunk is missing", () => {
    const buffer = new Uint8Array(24);
    const view = new DataView(buffer.buffer);
    buffer.set([0x52, 0x49, 0x46, 0x46], 0);
    view.setUint32(4, 16, true);
    buffer.set([0x57, 0x41, 0x56, 0x45], 8);
    buffer.set([0x64, 0x61, 0x74, 0x61], 12); // data without fmt
    view.setUint32(16, 4, true);

    expect(() => decodeWav(buffer)).toThrowError(PiperSynthesisError);
    try {
      decodeWav(buffer);
    } catch (err: unknown) {
      const error = err as PiperSynthesisError;
      expect(error.code).toBe("DECODE_FAILED");
      expect(error.message).toContain("Missing required 'fmt ' chunk");
    }
  });

  it("throws DECODE_FAILED when audio format is not PCM", () => {
    const dataSize = 4;
    const totalSize = 44 + dataSize;
    const buffer = new Uint8Array(totalSize);
    const view = new DataView(buffer.buffer);
    buffer.set([0x52, 0x49, 0x46, 0x46], 0);
    view.setUint32(4, totalSize - 8, true);
    buffer.set([0x57, 0x41, 0x56, 0x45], 8);
    buffer.set([0x66, 0x6d, 0x74, 0x20], 12);
    view.setUint32(16, 16, true);
    view.setUint16(20, 3, true); // Format 3 = IEEE Float, not PCM
    view.setUint16(22, 1, true);
    view.setUint32(24, 22050, true);
    view.setUint32(28, 88200, true);
    view.setUint16(32, 4, true);
    view.setUint16(34, 32, true);
    buffer.set([0x64, 0x61, 0x74, 0x61], 36);
    view.setUint32(40, dataSize, true);

    expect(() => decodeWav(buffer)).toThrowError(PiperSynthesisError);
    try {
      decodeWav(buffer);
    } catch (err: unknown) {
      const error = err as PiperSynthesisError;
      expect(error.code).toBe("DECODE_FAILED");
      expect(error.message).toContain("Unsupported audio format");
    }
  });

  it("throws DECODE_FAILED when 'data' chunk is missing or empty", () => {
    const buffer = new Uint8Array(36);
    const view = new DataView(buffer.buffer);
    buffer.set([0x52, 0x49, 0x46, 0x46], 0);
    view.setUint32(4, 28, true);
    buffer.set([0x57, 0x41, 0x56, 0x45], 8);
    buffer.set([0x66, 0x6d, 0x74, 0x20], 12);
    view.setUint32(16, 16, true);
    view.setUint16(20, 1, true);
    view.setUint16(22, 1, true);
    view.setUint32(24, 22050, true);
    view.setUint32(28, 44100, true);
    view.setUint16(32, 2, true);
    view.setUint16(34, 16, true);

    expect(() => decodeWav(buffer)).toThrowError(PiperSynthesisError);
    try {
      decodeWav(buffer);
    } catch (err: unknown) {
      const error = err as PiperSynthesisError;
      expect(error.code).toBe("DECODE_FAILED");
      expect(error.message).toContain("Missing or empty 'data' chunk");
    }
  });
});
